import { OnboardingStep } from './types';

export const onboardingSteps: OnboardingStep[] = [
    {
        id: 'age',
        type: 'age',
        title: 'How old are you?',
        subtitle: 'We need to verify your age to continue',
    },
    {
        id: 'content-type',
        type: 'content-type',
        title: 'What represents your content?',
        subtitle: 'Select the category that best fits your style',
        options: [
            '📸 Lifestyle',
            '😂 Comedy',
            '📚 Education',
            '💻 Tech',
            '💪 Fitness',
            '💄 Beauty',
            '🎮 Gaming',
            '🎵 Music',
            '✈️ Travel',
            '🍔 Food',
            '👗 Fashion',
            '🎨 Art & Design',
            '🎬 Movies/TV',
            '🚗 Automotive',
            '🐶 Pets'
        ],
        multiSelect: false,
    },
    {
        id: 'brand-preference',
        type: 'brand-preference',
        title: 'What deals do you want?',
        subtitle: 'Select at least 2 types of brands (or Any)',
        options: [
            'Any',
            '👗 Fashion',
            '👟 Sneakers',
            '⚽ Sports',
            '💻 Technology',
            '🎲 Gambling',
            '🧴 Skincare',
            '🥤 Beverages',
            '📱 Apps/Software',
            '💸 Finance',
            '🎮 Gaming',
            '🏥 Health & Wellness',
            '🏋️ Fitness & Gym',
            '💊 Supplements',
            '🏠 Home & Garden',
            '🚗 Automotive',
            '🐶 Pets',
            '₿ Crypto & Web3',
            '📚 Books & Literature',
            '🎟️ Events & Tickets',
            '🎵 Music & Audio',
            '✈️ Travel & Hotels'
        ],
        multiSelect: true,
        minSelection: 2,
    },
    {
        id: 'social-connect',
        type: 'social-connect',
        title: 'Connect your social accounts',
        subtitle: 'Link your platforms to track your influence',
    },
];
